name: Run Xunit Tests with Azure Cosmos DB Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Install Cosmos DB Emulator
      run: |
        wget https://aka.ms/cosmosdb-emulator-script -O install-cosmosdb-emulator.sh
        chmod +x install-cosmosdb-emulator.sh
        sudo ./install-cosmosdb-emulator.sh

    - name: Start Cosmos DB Emulator
      run: sudo service cosmosdb-emulator start

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x  # Use the version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test --logger "trx;LogFileName=testresults.trx"  # Adjust the command based on your test project structure and configuration
