name: Python Script Action

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    name: Run Python Script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the Python version you need, like 3.6, 3.7, etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements for your script

    - name: Run Python script
      run: python path/to/your_script.py  # Replace "path/to/your_script.py" with the actual path to your script
