name: Run Xunit Tests with Cosmos DB Emulator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure Cosmos DB Emulator
      run: |
        wget https://aka.ms/cosmosdb-emulator -O cosmosdbemulator.msi
        sudo apt-get update
        sudo apt-get install -y wine
        wine msiexec /i cosmosdbemulator.msi /q

    - name: Start Cosmos DB Emulator
      run: wine "C:\\Program Files\\Azure Cosmos DB Emulator\\CosmosDB.Emulator.exe" /EnableTableEndpoint

    - name: Wait for Cosmos DB Emulator to start
      run: sleep 30



