name: Install Azure Cosmos DB Emulator using Wine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Wine
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install wine64 wine32

      - name: Download Azure Cosmos DB Emulator installer
        run: wget -q https://aka.ms/cosmosdb-emulator -O cosmosdb-emulator.exe

      - name: Install Azure Cosmos DB Emulator
        run: wine cosmosdb-emulator.exe /quiet

      - name: Run Cosmos DB Emulator
        run: wine start CosmosDB.Emulator.exe

      - name: Install Wine Gecko
        run: wineboot --init && sleep 10 && wineserver -w

      - name: Run Cosmos DB Emulator (Headless)
        run: wine CosmosDB.Emulator.exe /headless
